name: Paper

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-figures:
    name: Update figures
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          ref: ${{ github.head_ref || github.ref }}

      - uses: PalisadeResearch/ci-action@master
        with:
          github_access_token: ${{ github.token }}

      - run: ninja figures

      - name: Commit updated figures if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "ðŸ“Š Figures are out of date, committing regenerated versions..."
            git config user.name "github-actions-bot-"
            git config user.email "github-actions-bot-@bot.noreply.github.com"
            git add -A
            git commit -m "chore: regenerate figures"
            git push
          else
            echo "âœ… Figures are up to date."
          fi

  paper:
    name: Build paper
    needs: update-figures
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          ref: ${{ github.head_ref || github.ref }}

      - uses: PalisadeResearch/ci-action@master
        with:
          github_access_token: ${{ github.token }}

      - run: ninja paper

      - uses: actions/upload-artifact@v4
        with:
          name: paper-latex
          path: paper-latex/main.pdf

      - uses: actions/upload-artifact@v4
        with:
          name: paper-typst
          path: paper-typst/main.pdf

      - name: Upload paper to release
        if: github.ref == 'refs/heads/main'
        run: |
          gh release delete --cleanup-tag -y latest || true
          mkdir out
          cp paper-latex/main.pdf out/latex.pdf
          cp paper-typst/main.pdf out/typst.pdf
          gh release create latest out/*
